# Generated by Django 4.2.7 on 2023-11-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpeapp', '0002_news_categorytype_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
