# Generated by Django 4.2.7 on 2023-12-07 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpeapp', '0004_sabscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sabscription',
            new_name='Subscription',
        ),
    ]
